apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    name: {{ .Values.apiName }}
  name: {{ .Values.apiName }}
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 3333
  selector:
    name: {{ .Values.apiName }}
status:
  loadBalancer: {}
