apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-{{ .Values.prNumber }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
   - http:
      paths:
      - path: "/{{ .Values.prNumber }}"
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.htmlName }}
            port:
              number: 3334
