apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    name: {{ .Values.htmlName }}
  name: {{ .Values.htmlName }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 3334
  selector:
    name: {{ .Values.htmlName }}
status:
  loadBalancer: {}
