on:
  pull_request:
    types: [closed]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: klausazurepoc
  CLUSTER_NAME: azure-poc-cluster
  CLUSTER_RESOURCE_GROUP: azure-poc
  NAMESPACE: pr-${{ github.event.pull_request.number }}

jobs:
  destroy-pr:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      - uses: azure/setup-helm@v3
        with:
          version: '3.5.3'
      - run: |
          helm uninstall ${{ env.NAMESPACE }} --namespace=${{ env.NAMESPACE }}
      # Delete namespace
      - run: |
          kubectl delete namespace ${{ env.NAMESPACE }}
